### ISSUE TITLE
/api/get-constants接口超时

### ISSUE THREAD

**Issue by aogg** [electerm/electerm-web#12]
### electerm-web Version and download file extension(electerm-web版本和下载文件后缀)

zxdong262/electerm-web

### Platform detail (平台详情)

docker

### What steps will reproduce the bug?(重新问题的详细步骤)

GET /chunk/zmodem-ts-2.38.65-1da997d2.js 304 - - 1.657 ms
GET /chunk/vscode-icons-js-2.38.65-da48f89a.js 304 - - 1.934 ms
GET /chunk/react-utils-2.38.65-7606d335.js 304 - - 2.000 ms
GET /api/get-constants 401 16 - 2.553 ms
POST /api/login 401 14 - 2.598 ms
POST /api/login 200 155 - 153.405 ms
GET /css/2.38.65-index.css 304 - - 1.883 ms
GET /css/2.38.65-basic.css 304 - - 1.500 ms
POST /api/login 200 155 - 11.261 ms
GET /api/get-constants - - - - ms
GET /api/get-constants - - - - ms
POST /api/login 200 155 - 7.455 ms
GET /api/get-constants - - - - ms
POST /api/login 200 155 - 6.001 ms
GET /api/get-constants - - - - ms

### What should have happened?(期望的结果)

不要超时

**Comment by zxdong262** [comment]
可以发一下运行命令等细节吗，注意不要泄露信息

**Comment by aogg** [comment]
已解决

用你们容器部署的，共享文件夹只有logs文件夹，没有user文件夹，然后就一直转圈，好歹报个错吧

```
# change $(pwd)/data to any folder you want to store data
# to use same data as desktop electerm
# for Mac OS modify $(pwd)/electerm-web-data to "/Users/<your-user-name>/Library/Application Support/electerm"
# for Linux OS modify $(pwd)/electerm-web-data to "/home/<your-user-name>/.config/electerm"
# for Windows OS modify $(pwd)/electerm-web-data to "C:\\Users\\<your-user-name>\\AppData\\Roaming\\electerm"

# SERVER_SECRET, SERVER_PASS, ENABLE_AUTH are optional,
# when ENABLE_AUTH enabled, would require login with SERVER_PASS when visit
# SERVER_SECRET is used to encrypt data, if not set, would use default value
# Should change some_server_secret to some complicated secret string

docker run --init -v $(pwd)/electerm-web-data:/home/electerm/data \
  -e "DB_PATH=/home/electerm/data" \
  -e "HOST=0.0.0.0" \
  -e "SERVER=http://127.0.0.1:8082" \
# -e "SERVER_SECRET=some_server_secret" \
# -e "SERVER_PASS=password_to_login" \
# -e "ENABLE_AUTH=1" \  
  -p 8082:5577 \
  zxdong262/electerm-web
```
