### ISSUE TITLE
大佬，有计划提供 docker 镜像吗？

### ISSUE THREAD

**Issue by loveqianool** [electerm/electerm-web#2]
方便在多平台部署。

**Comment by zxdong262** [comment]
会有的，可能得一段时间，目前还在移植开发阶段，还未通过基本测试

**Comment by zxdong262** [comment]
可以了，https://github.com/electerm/electerm-web-docker

**Comment by jihaomail** [comment]
谢谢，刚要找docker发现2个小时前发布了，感谢
