### ISSUE TITLE
无法复制到系统剪贴板

### ISSUE THREAD

**Issue by fnhchaiying** [electerm/electerm-web#6]
### electerm-web Version and download file extension(electerm-web版本和下载文件后缀)

docker image: billchurch/webssh2:latest

### Platform detail (平台详情)

win10 chrome

### What steps will reproduce the bug?(重新问题的详细步骤)

chrome浏览器打终端，复制文字
操作系统上打开notepad，粘贴后发现不是复制从浏览器中复制的内容

### What should have happened?(期望的结果)

可从终端复制文字到操作系统

**Comment by zxdong262** [comment]
感谢反馈，已经在最新版修复
