### ISSUE TITLE
ctrl+v快捷键与vim快捷键冲突

### ISSUE THREAD

**Issue by fnhchaiying** [electerm/electerm-web#7]
### electerm-web Version and download file extension(electerm-web版本和下载文件后缀)

docker image: billchurch/webssh2:latest

### Platform detail (平台详情)

windows 10 ,chrome

### What steps will reproduce the bug?(重新问题的详细步骤)

在终端上进入vim后无法通过ctrl+v进入vim列模式

### What should have happened?(期望的结果)

无快捷键冲突

**Comment by zxdong262** [comment]
感谢反馈，已经在最新版修复
